### ISSUE TITLE
(fsInclude) Coerce features along with those selected by fs. method

### ISSUE THREAD

**Issue by dantylee** [tpq/exprso#13]
I've been making great use of the plMonteCarlo in combination with various fs.methods.    I would love to be able to specify (by name) a subset of the covariates that could be forced into every model along with the features selected  (e.g. , age, sex, ancestry, etc).       Currently, I can include them as potentially selectable features, but there are several good reasons one might want to force them to be included (especially when working with a "balanced" training set).

**Comment by tpq** [comment]
Hm. Let me see if I understand this right. Do you want a way to guarantee that certain features will always be included _in addition to_ the selected features?

**Comment by dantylee** [comment]
Yes, exactly!

**Comment by tpq** [comment]
Hm. Is it usually annotation data that you want to include as features? (i.e., data included in the `@annot` slot)? I'll be opening `exprso` again soon to tweak a couple things. I think this is doable.

**Comment by dantylee** [comment]
Yes, exactly.   It would be ideal if a subset of the annotations could be
supplied (by name) and coerced into the feature set (along with those
selected by the fs.method).

**Comment by tpq** [comment]
In the newest version of exprso, you can accomplish this using the `fsInclude` method. This takes three arguments: (a) object - the `ExprsArray` object, (b) top - as all others, and (c) include - a character string specifying the features you want to include.

For your use case, it would work like this: First, make sure your annotations are represented as **numeric** features in the `@exprs` slot. Second, perform feature selection on the training set as you would normally (e.g., `fsStats(array.test, top = 0, how = "t.test")`). Third, call `fsInclude` on the result of the first feature selection, specifying the features you want to include. Fourth, `build` as you would normally.

In this way, the top N features provided to `fsInclude` (via argument `include`) will be the top N features called by `build`. Then, the remaining features will follow the order selected by the first round of feature selection (e.g., `fsStats`). Let me know if this requires further clarification.
