### ISSUE TITLE
Tagging fs_method into objects created by plMonteCarlo and plNested

### ISSUE THREAD

**Issue by dantylee** [tpq/exprso#14]
I'm in a situation where I'm creating SVMs with several fsMethods (t-test, ks-test, mrmre, eBayes), each time using a separate call of plMonteCarlo.     Each call produces an object.    It would be fairly useful (to me) if the fsMethod supplied to plMonteCarlo was also tagged in the resulting object.  

The reason being.... I'm conjoining the resulting objects into a single object.   Then I'm passing it through a pipeFilter to select some "bests" and binding them into a single ensemble for use in a withheld sample.     I'd like to know which fsMethods were "selected" in the ensemble.

**Comment by tpq** [comment]
I agree, this is actually quite important. Feature now added!
