### ISSUE TITLE
(build.) randomForest tryCatch issue

### ISSUE THREAD

**Issue by tpq** [tpq/exprso#2]
Should embed `tryCatch` statement within `fsRandomForest` to return `acc=1` instead of throwing error and crashing script.

**Comment by tpq** [comment]
Initial bug report: 

> When running plMonteCarlo with random forest and a small sample size, the pipeline frequently just freeezes and sometimes provides an error indicating that there is insufficient number (1?) of members of both classes.

**Comment by dantylee** [comment]
A similar issue.    Sometimes plMonteCarlo bootstrapper will pull a subsample., and for that subsample, a particular feature (gene, more commonly SNPs) will be zero variance (all identical).    This poses a problem for t-test and apparently for MRMRe.    At least I think this is the problem for MRMRe, as the following error occurs stochastically.  (Will post t-test error when available)

Error in .local(.Object, ...) : 
  data columns must be either of numeric, ordered factor or Surv type
In addition: There were 50 or more warnings (use warnings() to see the first 50)

 Can you perhaps filter out zero variance features before applying the fs.method?

**Comment by tpq** [comment]
I am pretty sure that this error should not occur with the newest version of the t-test. Do you mean (based on the code) that the eBayes fails? Do you think the problem is zero variance across all samples or zero variance within one of the experimental groups (CASES _or_ CONTROLS)?

**Comment by dantylee** [comment]
My apologies.   I did mean MRMRe, because skipping this method appears to have fixed the problem.   I suspect that plMonte sometime gives a sample where one or more SNPs in the matrix is all same value (either 0, 1, or 2) across both cases and controls.

**Comment by tpq** [comment]
Hey Dan, sorry for the delay. I'll finally be catching up with exprso work over the next couple of weeks. I am unable to reproduce your mRMRe error. As far as I can tell, mRMRe will automatically filter zero-variance features on its own.

In re-reading the error, my guess is that you are passing non-numeric data (i.e., annotation data) through t-test/mRMRe/etc. Let me know if you encounter this error again after ensuring all annotation data is coded numerically (e.g., coding male/female as 0/1).

**Comment by tpq** [comment]
Failed feature selections and model builds now dump DEBUG.RData file to help debug.
